### ISSUE TITLE
🔨 [Refactor] 7차 세미나 과제

### ISSUE THREAD

**Issue by wjdalswl** [NOW-SOPT-iOS-Part/JeongMinJi-assignment#9]
## 📝 개요
- SOLID, MVVM 패턴, RxSwift, DI를 사용해서 티빙과제를 리펙토링하기

## ✔️ To-Do
- [x] SOLID 사용해서 티빙과제를 리펙토링하기
- [x] MVVM 패턴 사용해서 티빙과제를 리펙토링하기
- [x] RxSwift 사용해서 티빙과제를 리펙토링하기
- [ ] DI를 사용해서 티빙과제를 리펙토링하기
